package version

import (
	"errors"
	"testing"
)

// Every ordering row was machine-generated by an oracle whose normalize()
// half passes composer's own test data providers 98/98; the one exception is
// the uppercase-STABLE trap, derived from verbatim source (composer's suite
// has no -stable row) and marked below. The trap rows worth reading:
// patch > stable, STABLE < dev < stable, and the date-branch padding gap.
func TestComposer_Compare(t *testing.T) {
	cases := []struct {
		a, b string
		want int
		err  bool
	}{
		{a: "v1.2.3", b: "1.2.3", want: 0},
		{a: "1.0", b: "1.0.0.0", want: 0},
		{a: "1.0", b: "1.0.0", want: 0},
		{a: "1.0.1", b: "1.0", want: 1},
		{a: "1.2.3.4", b: "1.2.3.5", want: -1},
		{a: "00.01.03.04", b: "0.1.3.4", want: 0},
		{a: "1.0.0+build.99", b: "1.0.0", want: 0},
		{a: "1.0.0+foo", b: "1.0.0+bar", want: 0},
		{a: "1.0.0@dev", b: "1.0.0", want: 0},
		{a: "1.0.0 as 2.0.0", b: "1.0.0", want: 0},
		{a: "1.0.0-dev", b: "1.0.0", want: -1},
		{a: "1.0.0-alpha1", b: "1.0.0-dev", want: 1},
		{a: "1.0.0-beta1", b: "1.0.0-alpha1", want: 1},
		{a: "1.0.0-RC1", b: "1.0.0-beta1", want: 1},
		{a: "1.0.0", b: "1.0.0-RC1", want: 1},
		// THE ladder trap: a patch release outranks its stable.
		{a: "1.0.0-patch1", b: "1.0.0", want: 1},
		{a: "1.0.0-a1", b: "1.0.0-alpha1", want: 0},
		{a: "1.0.0-b1", b: "1.0.0-beta1", want: 0},
		{a: "1.0.0-p1", b: "1.0.0-pl1", want: 0},
		{a: "1.0.0-pl1", b: "1.0.0-patch1", want: 0},
		// Numeric, not lexical.
		{a: "1.0.0-beta2", b: "1.0.0-beta10", want: -1},
		{a: "1.0.0-beta", b: "1.0.0-beta1", want: -1},
		{a: "1.0.0-beta.2", b: "1.0.0beta2", want: 0},
		{a: "1.0.0_beta2", b: "1.0.0-beta2", want: 0},
		{a: "1.0.0.beta.2", b: "1.0.0-beta-2", want: 0},
		{a: "1.0.0-alpha3.1", b: "1.0.0-alpha3", want: 1},
		{a: "1.0.0-RC1", b: "1.0.0-rc1", want: 0},
		{a: "1.0.0-BETA1", b: "1.0.0-beta1", want: 0},
		{a: "1.0.0RC1dev", b: "1.0.0-RC1", want: -1},
		{a: "1.0.0-RC1-dev", b: "1.0.0-RC1", want: -1},
		// Uppercase STABLE escapes the case-SENSITIVE elision, lowercases,
		// matches nothing in the forms table and lands BELOW dev. Derived
		// from verbatim source and the oracle port, not from a running PHP
		// (composer's suite has no such row) — if a live PHP ever disagrees,
		// this row and the source both need rereading, together.
		{a: "1.0.0-STABLE", b: "1.0.0", want: -1},
		{a: "1.0.0-STABLE", b: "1.0.0-dev", want: -1},
		{a: "1.0.0-stable", b: "1.0.0", want: 0},
		// The date branch skips four-part padding, so two spellings of one
		// date compare unequal. Faithful, trap and all.
		{a: "2010-01-02", b: "2010.01.02", want: -1},
		{a: "1.x-dev", b: "1.999.999", want: 1},
		{a: "1.x-dev", b: "2.0.0", want: -1},
		{a: "master", b: "dev-master", want: 0},
		// Real symfony release train, strictly ascending.
		{a: "6.4.0-BETA1", b: "6.4.0-BETA2", want: -1},
		{a: "6.4.0-BETA3", b: "6.4.0-RC1", want: -1},
		{a: "6.4.0-RC1", b: "6.4.0", want: -1},
		{a: "6.4.0", b: "6.4.1", want: -1},
		// The laravel sentinel: 99999 is exactly the five-digit major cap.
		{a: "4.1.99999", b: "4.1.99999.9999", want: -1},
		{a: "4.2.0", b: "4.1.99999", want: 1},

		{a: "dev-master", b: "dev-master", want: 0},
		{a: "dev-master", b: "1.0.0", err: true},
		{a: "dev-master", b: "dev-feature-x", err: true},
		{a: "1.0.1-SNAPSHOT", b: "1.0.1", err: true},
		{a: "1.0.0-meh", b: "1.0.0", err: true},
		{a: "1.0.0.0.0", b: "1.0.0", err: true},
		{a: "", b: "1.0.0", err: true},
		{a: "feature-foo", b: "1.0.0", err: true},
		{a: "~1", b: "1.0.0", err: true},
		{a: "1.0.0-beta_1", b: "1.0.0", err: true},
	}

	for _, tc := range cases {
		got, err := Composer{}.Compare(tc.a, tc.b)
		if tc.err {
			if err == nil {
				t.Errorf("Compare(%q, %q) = %d, want error", tc.a, tc.b, got)
			} else if !errors.Is(err, ErrInvalid) {
				t.Errorf("Compare(%q, %q) error %v does not wrap ErrInvalid", tc.a, tc.b, err)
			}
			continue
		}
		if err != nil {
			t.Errorf("Compare(%q, %q): %v", tc.a, tc.b, err)
			continue
		}
		if got != tc.want {
			t.Errorf("Compare(%q, %q) = %d, want %d", tc.a, tc.b, got, tc.want)
		}
		if rev, err := (Composer{}).Compare(tc.b, tc.a); err != nil || rev != -tc.want {
			t.Errorf("Compare(%q, %q) = %d, %v — reverse row, want %d", tc.b, tc.a, rev, err, -tc.want)
		}
	}
}
