package dirscan

import (
	"testing"
)

// Written before cargolock exists, and driving Parse rather than the parser:
// the recurring defect this repo keeps hitting is a cataloger with an
// exhaustive test of its own that nothing ever calls. Delete the KindCargoLock
// arm and this goes red, because the manifest falls through to default and
// becomes an Unread.

const cargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "assay-fixture"
version = "0.1.0"
dependencies = [
 "libgit2-sys",
 "time",
]

[[package]]
name = "libgit2-sys"
version = "0.16.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f79cd4b8dc7d0d2a0d9e5b1b1e5f2c8b7d1a3e4f5061728394a5b6c7d8e9f001"

[[package]]
name = "time"
version = "0.3.35"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaa1c0b2d3e4f50617283940a5b6c7d8e9f0011223344556677889900aabbccdd"
`

func TestParse_CargoLockReachesTheDispatch(t *testing.T) {
	root := writeTree(t, map[string]string{"Cargo.lock": cargoLock})

	version, location := findPackage(t, root, "libgit2-sys")
	if version != "0.16.1" {
		t.Errorf("libgit2-sys version = %q, want 0.16.1", version)
	}
	if location != "Cargo.lock" {
		t.Errorf("location = %q, want Cargo.lock", location)
	}
}

func TestParse_CargoLockEcosystemIsCratesIO(t *testing.T) {
	root := writeTree(t, map[string]string{"Cargo.lock": cargoLock})

	target, _, _, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	for _, p := range target.Packages {
		// "crates.io" is the OSV ecosystem key, and it is not the purl type:
		// the purl says cargo. Getting this wrong is a silent miss — every
		// lookup lands in a bucket that does not exist and reports clean —
		// so it is asserted on the package rather than left to the store.
		if p.Ecosystem != "crates.io" {
			t.Errorf("%s: ecosystem = %q, want crates.io", p.Name, p.Ecosystem)
		}
		if want := "pkg:cargo/" + p.Name + "@" + p.Version; p.PURL != want {
			t.Errorf("%s: PURL = %q, want %q", p.Name, p.PURL, want)
		}
	}
}

// The root package is the crate being scanned, not a dependency of it. It is
// counted, because it IS a component of the tree — unlike npm's "" key, which
// names the project and is skipped before the count — and because a workspace
// member can carry advisories of its own once published.
func TestParse_CargoLockCountsEveryPackageBlock(t *testing.T) {
	root := writeTree(t, map[string]string{"Cargo.lock": cargoLock})

	_, stats, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(found.Read) != 1 || found.Read[0].Kind != KindCargoLock {
		t.Fatalf("Read = %+v, want one Cargo.lock entry", found.Read)
	}
	if stats.Components != 3 || stats.Cataloged != 3 {
		t.Errorf("stats = %d components, %d cataloged; want 3 and 3",
			stats.Components, stats.Cataloged)
	}
}
