package dirscan

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// These tests drive Parse, not the parsers underneath it, and they are written
// before those parsers exist on purpose. CLAUDE.md's "The helper is covered;
// nothing calls it" section names the defect they are here to prevent: a new
// cataloger with an exhaustive table-driven test of its own, and nothing
// anywhere asserting that the dispatch which is supposed to reach it does.
// Delete a case from parseManifest's switch and every test below must go red —
// the manifest falls through to the default arm and becomes an Unread instead
// of packages, which is an observable difference rather than a rearrangement.

// writeTree writes each name/content pair into a fresh directory and returns
// its root. Names are slash-separated relative paths.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, body := range files {
		full := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("mkdir for %s: %v", name, err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	return root
}

// findPackage returns the package with the given name, or fails.
func findPackage(t *testing.T, root string, name string) (version, location string) {
	t.Helper()
	target, _, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	// An Unread here means the dispatch did not reach a parser at all, which
	// is the exact failure these tests exist to catch. Naming it beats a bare
	// "package not found" three lines later.
	for _, u := range found.Unread {
		t.Errorf("unexpected unread manifest %s: %s", u.Path, u.Reason)
	}
	for _, p := range target.Packages {
		if p.Name == name {
			if len(p.Locations) != 1 {
				t.Fatalf("%s: want exactly one location, got %d", name, len(p.Locations))
			}
			return p.Version, p.Locations[0].Path
		}
	}
	var got []string
	for _, p := range target.Packages {
		got = append(got, p.Name)
	}
	t.Fatalf("no package named %q; got %v", name, got)
	return "", ""
}

const yarnV1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scoped-fixture/widget@^2.0.0":
  version "2.4.6"
  resolved "https://registry.yarnpkg.com/@scoped-fixture/widget/-/widget-2.4.6.tgz"
  integrity sha512-deadbeef

left-pad@^1.0.0, left-pad@~1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz"
`

func TestParse_YarnLockV1ReachesTheDispatch(t *testing.T) {
	root := writeTree(t, map[string]string{"yarn.lock": yarnV1})

	version, location := findPackage(t, root, "left-pad")
	if version != "1.3.0" {
		t.Errorf("left-pad version = %q, want 1.3.0", version)
	}
	// The location is the manifest path relative to the scanned root, not the
	// absolute path the parser was handed — relocate() has to run for yarn.lock
	// the same as for every other kind.
	if location != "yarn.lock" {
		t.Errorf("left-pad location = %q, want yarn.lock", location)
	}

	// A scoped name is where a hand-written yarn parser goes wrong: the name
	// itself starts with @, so splitting on the FIRST @ yields "" and a range
	// of "scoped-fixture/widget@^2.0.0".
	if version, _ := findPackage(t, root, "@scoped-fixture/widget"); version != "2.4.6" {
		t.Errorf("scoped package version = %q, want 2.4.6", version)
	}
}

func TestParse_YarnLockIsCountedAsRead(t *testing.T) {
	root := writeTree(t, map[string]string{"yarn.lock": yarnV1})

	_, stats, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(found.Read) != 1 {
		t.Fatalf("Read = %+v, want exactly one entry", found.Read)
	}
	if found.Read[0].Kind != KindYarnLock {
		t.Errorf("Kind = %q, want %q", found.Read[0].Kind, KindYarnLock)
	}
	if found.Read[0].Components != 2 {
		t.Errorf("Components = %d, want 2", found.Read[0].Components)
	}
	if stats.Cataloged != 2 {
		t.Errorf("Cataloged = %d, want 2", stats.Cataloged)
	}
}

const pipfileLock = `{
    "_meta": {"hash": {"sha256": "abc"}},
    "default": {
        "django": {"version": "==3.2.19", "index": "pypi"},
        "from-a-git-url": {"git": "https://example.invalid/x.git", "ref": "aaaa"}
    },
    "develop": {
        "pytest-fixture-only": {"version": "==6.2.4"}
    }
}
`

func TestParse_PipfileLockReachesTheDispatch(t *testing.T) {
	root := writeTree(t, map[string]string{"Pipfile.lock": pipfileLock})

	if version, location := findPackage(t, root, "django"); version != "3.2.19" || location != "Pipfile.lock" {
		t.Errorf("django = %q at %q, want 3.2.19 at Pipfile.lock", version, location)
	}
	// develop is not a second file and not optional: a dev-only dependency is
	// still installed in CI, which is where a scan runs.
	if version, _ := findPackage(t, root, "pytest-fixture-only"); version != "6.2.4" {
		t.Errorf("develop package version = %q, want 6.2.4", version)
	}
}

func TestParse_PipfileLockVCSEntryIsCountedNotDropped(t *testing.T) {
	root := writeTree(t, map[string]string{"Pipfile.lock": pipfileLock})

	_, stats, _, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	// Three entries, two usable. The git-pinned one has no version a comparer
	// can place inside a range, so it is counted and skipped rather than
	// dropped — Components == Cataloged + skips is the invariant every
	// cataloger in this repo holds.
	if stats.Components != 3 || stats.Cataloged != 2 || stats.SkippedNoVersion != 1 {
		t.Errorf("stats = %d components, %d cataloged, %d skipped; want 3/2/1",
			stats.Components, stats.Cataloged, stats.SkippedNoVersion)
	}
}

const shrinkwrap = `{
  "name": "fixture",
  "lockfileVersion": 3,
  "packages": {
    "": {"name": "fixture", "version": "1.0.0"},
    "node_modules/only-in-shrinkwrap": {"version": "9.8.7"}
  }
}
`

func TestParse_NPMShrinkwrapRoutesToTheNPMParser(t *testing.T) {
	root := writeTree(t, map[string]string{"npm-shrinkwrap.json": shrinkwrap})

	version, location := findPackage(t, root, "only-in-shrinkwrap")
	if version != "9.8.7" {
		t.Errorf("version = %q, want 9.8.7", version)
	}
	if location != "npm-shrinkwrap.json" {
		t.Errorf("location = %q, want npm-shrinkwrap.json", location)
	}
}

// D103: pnpm-lock.yaml and yarn berry's yarn.lock are read now, not refused.
// This section drives that through Parse first, per CLAUDE.md's "the helper
// is covered; nothing calls it" - the fixtures below exercise pnpmlock.Parse
// and the berry half of yarnlock.Parse directly too (pnpmlock_test.go,
// yarnlock/berry_test.go), but nothing there can catch dirscan's own dispatch
// falling back to the old refusal, or losing the local/git/malformed skip
// classification on the way through relocate(). Deleting either KindPnpmLock
// or the berry branch of the KindYarnLock arm must turn every assertion below
// red: packages vanish, Unread reappears, or the skip disclosure goes silent.

const pnpmCallerFixture = `lockfileVersion: '9.0'

packages:

  widget-core@2.4.6:
    resolution: {integrity: sha512-deadbeefdeadbeefdeadbeefdeadbeefdeadbeef==}

  '@scope-fixture/workspace-thing@0.0.0-use.local':
    resolution: {directory: packages/workspace-thing, type: directory}

  forked-dep@0.0.0:
    resolution: {type: git, repo: 'https://github.com/acme-org/forked-dep', commit: 9f3ab12deadbeef}
`

func TestParse_PnpmLockReachesTheDispatch(t *testing.T) {
	root := writeTree(t, map[string]string{"pnpm-lock.yaml": pnpmCallerFixture})

	target, stats, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	// The old refusal is gone: before D103 this same tree produced one
	// Unread entry and zero packages.
	if len(found.Unread) != 0 {
		t.Fatalf("Unread = %+v, want none — pnpm-lock.yaml is read now", found.Unread)
	}
	if len(found.Read) != 1 || found.Read[0].Kind != KindPnpmLock {
		t.Fatalf("Read = %+v, want one KindPnpmLock entry", found.Read)
	}

	var got []string
	for _, p := range target.Packages {
		got = append(got, p.Name)
		if p.Name != "widget-core" {
			continue
		}
		if p.Version != "2.4.6" {
			t.Errorf("widget-core version = %q, want 2.4.6", p.Version)
		}
		if len(p.Locations) != 1 || p.Locations[0].Path != "pnpm-lock.yaml" {
			t.Errorf("widget-core locations = %+v, want [pnpm-lock.yaml]", p.Locations)
		}
		if p.Ecosystem != "npm" {
			t.Errorf("widget-core ecosystem = %q, want npm", p.Ecosystem)
		}
	}
	if len(target.Packages) != 1 {
		t.Fatalf("packages = %v, want widget-core alone (the workspace member and the git "+
			"dependency are not registry packages)", got)
	}

	// The local and git entries must both be visible — named, with why — even
	// though only the git one is a genuine coverage gap.
	byLine := map[string]string{}
	for _, u := range found.Unusable {
		if u.Path != "pnpm-lock.yaml" {
			t.Errorf("Unusable path = %q, want pnpm-lock.yaml", u.Path)
		}
		byLine[u.Line] = u.Reason
	}
	if _, ok := byLine["@scope-fixture/workspace-thing@0.0.0-use.local"]; !ok {
		t.Errorf("Unusable = %+v, want the workspace member named", found.Unusable)
	}
	if _, ok := byLine["forked-dep@0.0.0"]; !ok {
		t.Errorf("Unusable = %+v, want the git dependency named", found.Unusable)
	}

	// Only the git skip is a real coverage gap (SkippedNoVersion): the
	// workspace member must not inflate Stats at all, which is what keeps it
	// out of the target-incompleteness gate (D103's local/git/malformed
	// split).
	if stats.Components != 2 {
		t.Errorf("Components = %d, want 2 (widget-core cataloged, forked-dep skipped; "+
			"the workspace member is not a component)", stats.Components)
	}
	if stats.Cataloged != 1 {
		t.Errorf("Cataloged = %d, want 1", stats.Cataloged)
	}
	if stats.SkippedNoVersion != 1 {
		t.Errorf("SkippedNoVersion = %d, want 1 (the git dependency)", stats.SkippedNoVersion)
	}
}

const yarnBerryCallerFixture = `# This file is generated by running "yarn install" inside your project.
__metadata:
  version: 8
  cacheKey: 10

"gadget-lib@npm:^3.0.0":
  version: 3.1.4
  resolution: "gadget-lib@npm:3.1.4"

"@fixture-scope/workspace-pkg@workspace:packages/workspace-pkg":
  version: 0.0.0-use.local
  resolution: "@fixture-scope/workspace-pkg@workspace:packages/workspace-pkg"

"forked-tool@https://github.com/acme-org/forked-tool.git#commit=deadbeef1234":
  version: 2.0.0
  resolution: "forked-tool@https://github.com/acme-org/forked-tool.git#commit=deadbeef1234"
`

func TestParse_YarnBerryLockReachesTheDispatch(t *testing.T) {
	root := writeTree(t, map[string]string{"yarn.lock": yarnBerryCallerFixture})

	target, stats, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(found.Unread) != 0 {
		t.Fatalf("Unread = %+v, want none — berry yarn.lock is read now", found.Unread)
	}
	if len(found.Read) != 1 || found.Read[0].Kind != KindYarnLock {
		t.Fatalf("Read = %+v, want one KindYarnLock entry", found.Read)
	}

	if len(target.Packages) != 1 || target.Packages[0].Name != "gadget-lib" {
		t.Fatalf("packages = %+v, want gadget-lib alone", target.Packages)
	}
	if v, loc := target.Packages[0].Version, target.Packages[0].Locations[0].Path; v != "3.1.4" || loc != "yarn.lock" {
		t.Errorf("gadget-lib = %s at %s, want 3.1.4 at yarn.lock", v, loc)
	}

	byLine := map[string]string{}
	for _, u := range found.Unusable {
		byLine[u.Line] = u.Reason
	}
	if _, ok := byLine["@fixture-scope/workspace-pkg"]; !ok {
		t.Errorf("Unusable = %+v, want the workspace dependency named", found.Unusable)
	}
	if _, ok := byLine["forked-tool"]; !ok {
		t.Errorf("Unusable = %+v, want the https-normalized git dependency named", found.Unusable)
	}

	if stats.Components != 2 || stats.Cataloged != 1 || stats.SkippedNoVersion != 1 {
		t.Errorf("stats = %+v, want 2 components (1 cataloged, 1 skipped as no-version); "+
			"the workspace dependency must not be a component", stats)
	}
}

// A pnpm lockfile assay genuinely cannot read - not "recognized and
// deferred" any more, but really malformed - must still fail the scan.
// D11's untrustworthy-result ranking did not change; only which files earn
// it did.
func TestParse_MalformedPnpmLockStillFailsTheScan(t *testing.T) {
	root := writeTree(t, map[string]string{
		"pnpm-lock.yaml": "lockfileVersion: v6\n\npackages:\n  left-pad@1.3.0:\n    resolution: {integrity: sha512-x}\n",
	})

	target, _, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(target.Packages) != 0 {
		t.Errorf("packages = %+v, want none", target.Packages)
	}
	if len(found.Unread) != 1 || !found.Unread[0].Failed {
		t.Fatalf("Unread = %+v, want exactly one Failed entry", found.Unread)
	}
	if !strings.Contains(found.Unread[0].Reason, "lockfileVersion") {
		t.Errorf("Unread reason = %q, want it to name the bad lockfileVersion", found.Unread[0].Reason)
	}
	if !found.AnyFailed() {
		t.Error("AnyFailed() = false, want true")
	}
}

// A yarn.lock in neither dialect this parser knows - the D103 replacement for
// the old "it might be berry, refuse on principle" behaviour, now that berry
// itself is read. Falling back to the v1 parser here would silently report
// zero packages, exactly the failure mode this whole area exists to avoid.
func TestParse_UnknownYarnDialectStillFailsTheScan(t *testing.T) {
	root := writeTree(t, map[string]string{
		"yarn.lock": "some-package:\n  version \"1.0.0\"\n",
	})

	target, _, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(target.Packages) != 0 {
		t.Errorf("packages = %+v, want none", target.Packages)
	}
	if len(found.Unread) != 1 || !found.Unread[0].Failed {
		t.Fatalf("Unread = %+v, want exactly one Failed entry", found.Unread)
	}
	if !found.AnyFailed() {
		t.Error("AnyFailed() = false, want true")
	}
}

// A tree that assay CAN read alongside one it cannot is still an untrustworthy
// result: 2 outranks the content of the result (D11). The readable half must
// still be reported, though — refusing to say anything would lose findings the
// scan genuinely made. web/pnpm-lock.yaml here is malformed, not merely a
// format assay used to defer — pnpm-lock.yaml lost its blanket refusal in
// D103, so this fixture had to change to keep testing what it was written to
// test.
func TestParse_ReadableManifestAlongsideAnUnreadableOne(t *testing.T) {
	root := writeTree(t, map[string]string{
		"api/Pipfile.lock":   pipfileLock,
		"web/pnpm-lock.yaml": "lockfileVersion: v6\n\npackages:\n  left-pad@1.3.0:\n    resolution: {integrity: sha512-x}\n",
	})

	target, _, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if !found.AnyFailed() {
		t.Error("AnyFailed() = false; the pnpm lockfile went unread")
	}
	if len(found.Read) != 1 || found.Read[0].Path != "api/Pipfile.lock" {
		t.Errorf("Read = %+v, want the Pipfile.lock alone", found.Read)
	}
	var names []string
	for _, p := range target.Packages {
		names = append(names, p.Name)
	}
	if len(names) != 2 {
		t.Errorf("packages = %v, want the two the Pipfile.lock resolved", names)
	}
}
