package dirscan

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// These tests drive Parse, not the parsers underneath it, and they are written
// before those parsers exist on purpose. CLAUDE.md's "The helper is covered;
// nothing calls it" section names the defect they are here to prevent: a new
// cataloger with an exhaustive table-driven test of its own, and nothing
// anywhere asserting that the dispatch which is supposed to reach it does.
// Delete a case from parseManifest's switch and every test below must go red —
// the manifest falls through to the default arm and becomes an Unread instead
// of packages, which is an observable difference rather than a rearrangement.

// writeTree writes each name/content pair into a fresh directory and returns
// its root. Names are slash-separated relative paths.
func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, body := range files {
		full := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("mkdir for %s: %v", name, err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	return root
}

// findPackage returns the package with the given name, or fails.
func findPackage(t *testing.T, root string, name string) (version, location string) {
	t.Helper()
	target, _, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	// An Unread here means the dispatch did not reach a parser at all, which
	// is the exact failure these tests exist to catch. Naming it beats a bare
	// "package not found" three lines later.
	for _, u := range found.Unread {
		t.Errorf("unexpected unread manifest %s: %s", u.Path, u.Reason)
	}
	for _, p := range target.Packages {
		if p.Name == name {
			if len(p.Locations) != 1 {
				t.Fatalf("%s: want exactly one location, got %d", name, len(p.Locations))
			}
			return p.Version, p.Locations[0].Path
		}
	}
	var got []string
	for _, p := range target.Packages {
		got = append(got, p.Name)
	}
	t.Fatalf("no package named %q; got %v", name, got)
	return "", ""
}

const yarnV1 = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@scoped-fixture/widget@^2.0.0":
  version "2.4.6"
  resolved "https://registry.yarnpkg.com/@scoped-fixture/widget/-/widget-2.4.6.tgz"
  integrity sha512-deadbeef

left-pad@^1.0.0, left-pad@~1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz"
`

func TestParse_YarnLockV1ReachesTheDispatch(t *testing.T) {
	root := writeTree(t, map[string]string{"yarn.lock": yarnV1})

	version, location := findPackage(t, root, "left-pad")
	if version != "1.3.0" {
		t.Errorf("left-pad version = %q, want 1.3.0", version)
	}
	// The location is the manifest path relative to the scanned root, not the
	// absolute path the parser was handed — relocate() has to run for yarn.lock
	// the same as for every other kind.
	if location != "yarn.lock" {
		t.Errorf("left-pad location = %q, want yarn.lock", location)
	}

	// A scoped name is where a hand-written yarn parser goes wrong: the name
	// itself starts with @, so splitting on the FIRST @ yields "" and a range
	// of "scoped-fixture/widget@^2.0.0".
	if version, _ := findPackage(t, root, "@scoped-fixture/widget"); version != "2.4.6" {
		t.Errorf("scoped package version = %q, want 2.4.6", version)
	}
}

func TestParse_YarnLockIsCountedAsRead(t *testing.T) {
	root := writeTree(t, map[string]string{"yarn.lock": yarnV1})

	_, stats, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(found.Read) != 1 {
		t.Fatalf("Read = %+v, want exactly one entry", found.Read)
	}
	if found.Read[0].Kind != KindYarnLock {
		t.Errorf("Kind = %q, want %q", found.Read[0].Kind, KindYarnLock)
	}
	if found.Read[0].Components != 2 {
		t.Errorf("Components = %d, want 2", found.Read[0].Components)
	}
	if stats.Cataloged != 2 {
		t.Errorf("Cataloged = %d, want 2", stats.Cataloged)
	}
}

const pipfileLock = `{
    "_meta": {"hash": {"sha256": "abc"}},
    "default": {
        "django": {"version": "==3.2.19", "index": "pypi"},
        "from-a-git-url": {"git": "https://example.invalid/x.git", "ref": "aaaa"}
    },
    "develop": {
        "pytest-fixture-only": {"version": "==6.2.4"}
    }
}
`

func TestParse_PipfileLockReachesTheDispatch(t *testing.T) {
	root := writeTree(t, map[string]string{"Pipfile.lock": pipfileLock})

	if version, location := findPackage(t, root, "django"); version != "3.2.19" || location != "Pipfile.lock" {
		t.Errorf("django = %q at %q, want 3.2.19 at Pipfile.lock", version, location)
	}
	// develop is not a second file and not optional: a dev-only dependency is
	// still installed in CI, which is where a scan runs.
	if version, _ := findPackage(t, root, "pytest-fixture-only"); version != "6.2.4" {
		t.Errorf("develop package version = %q, want 6.2.4", version)
	}
}

func TestParse_PipfileLockVCSEntryIsCountedNotDropped(t *testing.T) {
	root := writeTree(t, map[string]string{"Pipfile.lock": pipfileLock})

	_, stats, _, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	// Three entries, two usable. The git-pinned one has no version a comparer
	// can place inside a range, so it is counted and skipped rather than
	// dropped — Components == Cataloged + skips is the invariant every
	// cataloger in this repo holds.
	if stats.Components != 3 || stats.Cataloged != 2 || stats.SkippedNoVersion != 1 {
		t.Errorf("stats = %d components, %d cataloged, %d skipped; want 3/2/1",
			stats.Components, stats.Cataloged, stats.SkippedNoVersion)
	}
}

const shrinkwrap = `{
  "name": "fixture",
  "lockfileVersion": 3,
  "packages": {
    "": {"name": "fixture", "version": "1.0.0"},
    "node_modules/only-in-shrinkwrap": {"version": "9.8.7"}
  }
}
`

func TestParse_NPMShrinkwrapRoutesToTheNPMParser(t *testing.T) {
	root := writeTree(t, map[string]string{"npm-shrinkwrap.json": shrinkwrap})

	version, location := findPackage(t, root, "only-in-shrinkwrap")
	if version != "9.8.7" {
		t.Errorf("version = %q, want 9.8.7", version)
	}
	if location != "npm-shrinkwrap.json" {
		t.Errorf("location = %q, want npm-shrinkwrap.json", location)
	}
}

// unreadableFormats are the lockfiles assay recognizes and cannot read. Each
// must be NAMED and must fail the scan: a repository whose only manifest is
// one of these has had none of its dependencies looked at, and reporting that
// as a clean exit 0 is the silent miss this project is built to refuse.
func TestParse_UnreadableLockfileIsNamedAndFailsTheScan(t *testing.T) {
	cases := []struct {
		name    string
		file    string
		body    string
		mustSay string
	}{
		{
			name:    "pnpm",
			file:    "pnpm-lock.yaml",
			body:    "lockfileVersion: \"9.0\"\n\nimporters:\n  .:\n    dependencies:\n      left-pad:\n        specifier: ^1.3.0\n        version: 1.3.0\n",
			mustSay: "YAML",
		},
		{
			name:    "uv",
			file:    "uv.lock",
			body:    "version = 1\n\n[[package]]\nname = \"django\"\nversion = \"3.2.19\"\n",
			mustSay: "TOML",
		},
		{
			name: "yarn berry",
			file: "yarn.lock",
			// Berry is YAML and shares the filename with v1. Reading it with
			// the v1 parser does not fail loudly — it quietly finds no
			// `version "x"` lines and reports zero packages, which is a clean
			// verdict over an unread file.
			body:    "# This file is generated by running \"yarn install\" inside your project.\n\n__metadata:\n  version: 8\n  cacheKey: 10\n\n\"left-pad@npm:^1.3.0\":\n  version: 1.3.0\n  resolution: \"left-pad@npm:1.3.0\"\n",
			mustSay: "berry",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := writeTree(t, map[string]string{tc.file: tc.body})

			target, _, found, err := Parse(root)
			if err != nil {
				t.Fatalf("Parse: %v", err)
			}
			if len(target.Packages) != 0 {
				t.Errorf("packages = %+v, want none — a format we cannot read must not produce any", target.Packages)
			}
			if len(found.Unread) != 1 {
				t.Fatalf("Unread = %+v, want exactly one entry", found.Unread)
			}
			u := found.Unread[0]
			if u.Path != tc.file {
				t.Errorf("Unread path = %q, want %q", u.Path, tc.file)
			}
			if !strings.Contains(u.Reason, tc.mustSay) {
				t.Errorf("Unread reason = %q, want it to name %q", u.Reason, tc.mustSay)
			}
			if !u.Failed {
				t.Error("Failed = false; an unreadable lockfile means this scan saw none of the tree's dependencies, which must reach exit 2")
			}
			if !found.AnyFailed() {
				t.Error("AnyFailed() = false, want true")
			}
		})
	}
}

// A tree that assay CAN read alongside one it cannot is still an untrustworthy
// result: 2 outranks the content of the result (D11). The readable half must
// still be reported, though — refusing to say anything would lose findings the
// scan genuinely made.
func TestParse_ReadableManifestAlongsideAnUnreadableOne(t *testing.T) {
	root := writeTree(t, map[string]string{
		"api/Pipfile.lock":   pipfileLock,
		"web/pnpm-lock.yaml": "lockfileVersion: \"9.0\"\n",
	})

	target, _, found, err := Parse(root)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if !found.AnyFailed() {
		t.Error("AnyFailed() = false; the pnpm lockfile went unread")
	}
	if len(found.Read) != 1 || found.Read[0].Path != "api/Pipfile.lock" {
		t.Errorf("Read = %+v, want the Pipfile.lock alone", found.Read)
	}
	var names []string
	for _, p := range target.Packages {
		names = append(names, p.Name)
	}
	if len(names) != 2 {
		t.Errorf("packages = %v, want the two the Pipfile.lock resolved", names)
	}
}
