package yarnlock

import (
	"strings"
	"testing"
)

// berryHeader is the __metadata block every fixture below needs so
// classifyDialect routes to parseBerry rather than the v1 scanner or
// ErrUnknownDialect.
const berryHeader = `# This file is generated by running "yarn install" inside your project.
__metadata:
  version: 8
  cacheKey: 10

`

// TestParse_BerrySplitResolution transcribes splitResolution's own rows from
// D103's adversarial table directly - the boundary-scanning rule (first "@"
// followed by lowercase letters then ":") is exactly what a patch:
// resolution's nested locator would break under the "split on the last @"
// rule syft uses instead.
func TestParse_BerrySplitResolution(t *testing.T) {
	cases := []struct {
		res      string
		wantName string
		wantProt string
		wantOK   bool
	}{
		{"lodash@npm:4.17.21", "lodash", "npm", true},
		{"@babel/cli@npm:7.27.1", "@babel/cli", "npm", true},
		{"typescript@patch:typescript@npm%3A5.9.2#builtin<compat/typescript>::version=5.9.2&hash=5786d5",
			"typescript", "patch", true},
		{"@yarnpkg/cli@workspace:packages/yarnpkg-cli", "@yarnpkg/cli", "workspace", true},
		{"pem@https://github.com/dexus/pem.git#commit=71dae334abcd", "pem", "https", true},
		{"$repo-utils@link:./scripts/repo-utils::locator=root-workspace%40workspace%3A.",
			"$repo-utils", "link", true},
		{"gatsby-plugin-algolia-docsearch@portal:./plugins/algolia-docsearch::locator=site%40workspace%3A.",
			"gatsby-plugin-algolia-docsearch", "portal", true},
		{"JSONStream@npm:1.3.5", "JSONStream", "npm", true},
		{"resolve@npm:1.9.0", "resolve", "npm", true},
		// No protocol boundary at all: a bare name, or a URL-encoded "npm%3A"
		// that must NOT satisfy the literal-":" requirement.
		{"just-a-name", "", "", false},
		{"typescript@npm%3A5.9.2", "", "", false},
	}
	for _, tc := range cases {
		t.Run(tc.res, func(t *testing.T) {
			name, proto, _, ok := splitResolution(tc.res)
			if ok != tc.wantOK || name != tc.wantName || proto != tc.wantProt {
				t.Errorf("splitResolution(%q) = (%q, %q, _, %v), want (%q, %q, _, %v)",
					tc.res, name, proto, ok, tc.wantName, tc.wantProt, tc.wantOK)
			}
		})
	}
}

func TestParse_BerryLodash(t *testing.T) {
	path := write(t, berryHeader+`"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
`)
	pkgs, _, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "lodash" || pkgs[0].Version != "4.17.21" {
		t.Fatalf("pkgs = %+v, want lodash@4.17.21", pkgs)
	}
}

// The name comes from the RESOLUTION, not the key - an aliased key names a
// package that does not exist on npm at all, and the resolution is the real
// one actually installed.
func TestParse_BerryAliasNameComesFromResolutionNotKey(t *testing.T) {
	path := write(t, berryHeader+`"@babel-baseline/cli@npm:@babel/cli@7.27.1":
  version: 7.27.1
  resolution: "@babel/cli@npm:7.27.1"
`)
	pkgs, _, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "@babel/cli" {
		t.Fatalf("pkgs = %+v, want @babel/cli, NOT @babel-baseline/cli", pkgs)
	}
}

// A patch: entry is silently absorbed - no Skipped entry, no Stats bump -
// because the npm: twin it patches already reports the same name and
// version. Silence here is deliberate (see parseBerry's own comment): naming
// every patch: entry would just repeat what the twin already says.
func TestParse_BerryPatchIsSilentWhenTheNpmTwinExists(t *testing.T) {
	path := write(t, berryHeader+`"typescript@npm:5.9.2":
  version: 5.9.2
  resolution: "typescript@npm:5.9.2"

"typescript@patch:typescript@npm%3A5.9.2#builtin<compat/typescript>::version=5.9.2&hash=5786d5":
  version: 5.9.2
  resolution: "typescript@patch:typescript@npm%3A5.9.2#builtin<compat/typescript>::version=5.9.2&hash=5786d5"
`)
	pkgs, stats, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "typescript" || pkgs[0].Version != "5.9.2" {
		t.Fatalf("pkgs = %+v, want typescript@5.9.2 alone", pkgs)
	}
	if stats.Components != 1 || stats.Cataloged != 1 {
		t.Errorf("stats = %+v, want the patch entry to leave no trace at all", stats)
	}
	if len(skipped) != 0 {
		t.Errorf("skipped = %+v, want none - the patch: entry is silent", skipped)
	}
}

func TestParse_BerryWorkspaceIsLocalSkip(t *testing.T) {
	path := write(t, berryHeader+`"@yarnpkg/cli@workspace:packages/yarnpkg-cli":
  version: 0.0.0-use.local
  resolution: "@yarnpkg/cli@workspace:packages/yarnpkg-cli"
`)
	pkgs, stats, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("pkgs = %+v, want none", pkgs)
	}
	if stats.Components != 0 {
		t.Errorf("Components = %d, want 0 - a workspace member is not a component", stats.Components)
	}
	if len(skipped) != 1 || skipped[0].Name != "@yarnpkg/cli" {
		t.Fatalf("skipped = %+v, want @yarnpkg/cli named", skipped)
	}
}

// A git dependency yarn has normalized into an https: resolution must be
// skipped even though its version: field looks perfectly plausible - that
// version is the fork's own self-declared one, not a registry release.
func TestParse_BerryHttpsGitResolutionSkipsDespitePlausibleVersion(t *testing.T) {
	path := write(t, berryHeader+`"pem@dexus/pem":
  version: 1.14.5
  resolution: "pem@https://github.com/dexus/pem.git#commit=71dae334abcd"
`)
	pkgs, stats, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("pkgs = %+v, want none — version: 1.14.5 must not be trusted", pkgs)
	}
	if stats.SkippedNoVersion != 1 {
		t.Errorf("stats = %+v, want 1 skipped as no-version", stats)
	}
	if len(skipped) != 1 || skipped[0].Name != "pem" {
		t.Fatalf("skipped = %+v, want pem named", skipped)
	}
}

// A $-prefixed name is real (a real fixture broke syft's alias regex on
// exactly this shape) - splitResolution must not care what character a name
// starts with, only where the protocol boundary is.
func TestParse_BerryDollarPrefixedLocalName(t *testing.T) {
	path := write(t, berryHeader+`"$repo-utils@workspace:scripts/repo-utils":
  version: 0.0.0-use.local
  resolution: "$repo-utils@link:./scripts/repo-utils::locator=root-workspace%40workspace%3A."
`)
	pkgs, _, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("pkgs = %+v, want none", pkgs)
	}
	if len(skipped) != 1 || skipped[0].Name != "$repo-utils" {
		t.Fatalf("skipped = %+v, want $repo-utils named", skipped)
	}
}

func TestParse_BerryPortalIsLocalSkip(t *testing.T) {
	path := write(t, berryHeader+`"gatsby-plugin-algolia-docsearch@portal:./plugins/algolia-docsearch":
  version: 0.0.0-use.local
  resolution: "gatsby-plugin-algolia-docsearch@portal:./plugins/algolia-docsearch::locator=site%40workspace%3A."
`)
	pkgs, _, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("pkgs = %+v, want none", pkgs)
	}
	if len(skipped) != 1 || skipped[0].Name != "gatsby-plugin-algolia-docsearch" {
		t.Fatalf("skipped = %+v, want the portal dependency named", skipped)
	}
}

func TestParse_BerryUppercaseName(t *testing.T) {
	path := write(t, berryHeader+`"JSONStream@npm:^1.3.0":
  version: 1.3.5
  resolution: "JSONStream@npm:1.3.5"
`)
	pkgs, _, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "JSONStream" || pkgs[0].Version != "1.3.5" {
		t.Fatalf("pkgs = %+v, want JSONStream@1.3.5 (case preserved)", pkgs)
	}
}

// A multi-descriptor key needs no parsing at all: every descriptor on it
// resolves to the one package the entry's own resolution: names.
func TestParse_BerryMultiDescriptorKeyIsOneEntry(t *testing.T) {
	path := write(t, berryHeader+`"a@npm:^7.0.0, a@npm:^7.10.4":
  version: 7.10.4
  resolution: "a@npm:7.10.4"
`)
	pkgs, stats, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "a" || pkgs[0].Version != "7.10.4" {
		t.Fatalf("pkgs = %+v, want a@7.10.4 once", pkgs)
	}
	if stats.Components != 1 {
		t.Errorf("Components = %d, want 1 - one entry, however many descriptors its key lists", stats.Components)
	}
}

// A document containing a genuine duplicate YAML key must still parse (the
// whole reason this reads via yaml.Node rather than a map decode) and dedupe
// to one package rather than emitting it twice.
func TestParse_BerryDuplicateKeyStillParsesAndDedupes(t *testing.T) {
	path := write(t, berryHeader+`"@types/qs@npm:6.9.4":
  version: 6.9.4
  resolution: "@types/qs@npm:6.9.4"

"@types/qs@npm:6.9.4":
  version: 6.9.4
  resolution: "@types/qs@npm:6.9.4"
`)
	pkgs, stats, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v — a duplicate key must not fail the whole document", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "@types/qs" || pkgs[0].Version != "6.9.4" {
		t.Fatalf("pkgs = %+v, want @types/qs@6.9.4 exactly once", pkgs)
	}
	if stats.Components != 1 || stats.Cataloged != 1 {
		t.Errorf("stats = %+v, want the duplicate absorbed silently", stats)
	}
}

// Two different versions of the same name are both real packages - dedupe is
// on name@version, never on the bare name.
func TestParse_BerryTwoVersionsOfSameNameBothKept(t *testing.T) {
	path := write(t, berryHeader+`"async@npm:^3.2.0":
  version: 3.2.6
  resolution: "async@npm:3.2.6"

"async@npm:^0.9.0":
  version: 0.9.2
  resolution: "async@npm:0.9.2"
`)
	pkgs, _, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	got := map[string]bool{}
	for _, p := range pkgs {
		got[p.Name+"@"+p.Version] = true
	}
	if !got["async@3.2.6"] || !got["async@0.9.2"] {
		t.Fatalf("pkgs = %+v, want both async@3.2.6 and async@0.9.2", pkgs)
	}
}

// An unquoted key with no protocol embedded in the key text at all -
// classification must come from resolution: alone, never the key.
func TestParse_BerryUnquotedKeyClassifiesFromResolution(t *testing.T) {
	path := write(t, berryHeader+`resolve@1.9.0:
  version: 1.9.0
  resolution: "resolve@npm:1.9.0"
`)
	pkgs, _, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "resolve" || pkgs[0].Version != "1.9.0" {
		t.Fatalf("pkgs = %+v, want resolve@1.9.0", pkgs)
	}
}

// A resolution with no recognizable protocol boundary at all is malformed,
// not silently dropped.
func TestParse_BerryUnrecognizableResolutionIsMalformed(t *testing.T) {
	path := write(t, berryHeader+`"broken-entry@npm:^1.0.0":
  version: 1.0.0
  resolution: "not-a-valid-resolution-string"
`)
	pkgs, stats, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("pkgs = %+v, want none", pkgs)
	}
	if stats.Components != 1 || stats.SkippedNoPURL != 1 {
		t.Errorf("stats = %+v, want 1 component skipped as no-purl", stats)
	}
	if len(skipped) != 1 {
		t.Fatalf("skipped = %+v, want one entry", skipped)
	}
	if !strings.Contains(skipped[0].Reason, "protocol boundary") {
		t.Errorf("Reason = %q, want it to name the missing protocol boundary", skipped[0].Reason)
	}
}

// An entry with no resolution: field at all is malformed for the same
// reason.
func TestParse_BerryEntryWithNoResolutionIsMalformed(t *testing.T) {
	path := write(t, berryHeader+`"no-resolution-field@npm:^1.0.0":
  version: 1.0.0
`)
	pkgs, stats, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("pkgs = %+v, want none", pkgs)
	}
	if stats.SkippedNoPURL != 1 {
		t.Errorf("stats = %+v, want 1 skipped as no-purl", stats)
	}
	if len(skipped) != 1 || skipped[0].Name != "no-resolution-field@npm:^1.0.0" {
		t.Fatalf("skipped = %+v, want the raw key named (no name could be resolved)", skipped)
	}
}

// An unrecognized protocol - not npm, not a known local protocol, not
// https, not patch - is a fourth, defensive disposition: visible rather
// than silently dropped, the same as a truly malformed entry.
func TestParse_BerryUnrecognizedProtocolIsMalformed(t *testing.T) {
	path := write(t, berryHeader+`"exotic-proto-pkg@npm:^1.0.0":
  version: 1.0.0
  resolution: "exotic-proto-pkg@conda:some-channel/exotic-proto-pkg"
`)
	pkgs, stats, skipped, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("pkgs = %+v, want none", pkgs)
	}
	if stats.SkippedNoPURL != 1 {
		t.Errorf("stats = %+v, want 1 skipped as no-purl", stats)
	}
	if len(skipped) != 1 || skipped[0].Name != "exotic-proto-pkg" {
		t.Fatalf("skipped = %+v, want exotic-proto-pkg named", skipped)
	}
}
