package yarnlock

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func write(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "yarn.lock")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	return path
}

// A header with no version line must be COUNTED, not dropped. Dropping it
// leaves Components below the number of entries the file declared, which
// breaks the Components == Cataloged + skips invariant the report relies on to
// say how much of a manifest it managed to use — and an entry that vanishes
// from every counter is indistinguishable from one that was never there.
func TestParse_HeaderWithoutAVersionIsCountedAsSkipped(t *testing.T) {
	path := write(t, `# yarn lockfile v1

resolution-failed@^1.0.0:
  resolved "https://registry.yarnpkg.com/resolution-failed/-/x.tgz"

left-pad@^1.0.0:
  version "1.3.0"
`)

	pkgs, stats, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "left-pad" {
		t.Fatalf("packages = %+v, want left-pad alone", pkgs)
	}
	if stats.Components != 2 {
		t.Errorf("Components = %d, want 2 — the versionless entry still exists", stats.Components)
	}
	if stats.SkippedNoVersion != 1 {
		t.Errorf("SkippedNoVersion = %d, want 1", stats.SkippedNoVersion)
	}
	if stats.Components != stats.Cataloged+stats.SkippedNoVersion {
		t.Errorf("invariant broken: %d components != %d cataloged + %d skipped",
			stats.Components, stats.Cataloged, stats.SkippedNoVersion)
	}
}

// A header this parser cannot turn into a name is the other half of the same
// invariant, and it takes a separate test because it fails at a different
// point: nameFromSpecs returns empty rather than the version line being
// missing, so a parser that keys "is an entry open" off the name alone drops
// it silently.
func TestParse_HeaderWithNoUsableNameIsCountedAsSkipped(t *testing.T) {
	path := write(t, `# yarn lockfile v1

"@nothing-after-the-scope":
  version "1.0.0"

left-pad@^1.0.0:
  version "1.3.0"
`)

	pkgs, stats, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("packages = %+v, want only the named one", pkgs)
	}
	if stats.Components != 2 || stats.SkippedNoVersion != 1 {
		t.Errorf("stats = %d components, %d skipped; want 2 and 1", stats.Components, stats.SkippedNoVersion)
	}
}

func TestParse_Names(t *testing.T) {
	cases := []struct {
		name   string
		header string
		want   string
	}{
		{"plain", `lodash@^4.17.0:`, "lodash"},
		{"several specs resolve to one package", `lodash@^4.17.0, lodash@~4.17.15:`, "lodash"},
		{"quoted", `"left-pad@^1.3.0":`, "left-pad"},
		{"scoped", `"@babel/core@^7.0.0":`, "@babel/core"},
		{"scoped, several specs", `"@babel/core@^7.0.0", "@babel/core@^7.1.0":`, "@babel/core"},
		// An alias resolves to the package actually installed, not to the
		// local name. See nameFromSpecs for why the alias is a false negative.
		{"aliased", `"aliased@npm:lodash@^4.0.0":`, "lodash"},
		{"aliased and scoped", `"my-core@npm:@babel/core@^7.0.0":`, "@babel/core"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := write(t, "# yarn lockfile v1\n\n"+tc.header+"\n  version \"1.0.0\"\n")
			pkgs, _, err := Parse(path)
			if err != nil {
				t.Fatalf("Parse: %v", err)
			}
			if len(pkgs) != 1 {
				t.Fatalf("packages = %+v, want exactly one", pkgs)
			}
			if pkgs[0].Name != tc.want {
				t.Errorf("name = %q, want %q", pkgs[0].Name, tc.want)
			}
			// The PURL is built from the same name, so a name bug that this
			// assertion alone would catch must not be able to hide there.
			if want := "pkg:npm/" + tc.want + "@1.0.0"; pkgs[0].PURL != want {
				t.Errorf("PURL = %q, want %q", pkgs[0].PURL, want)
			}
		})
	}
}

func TestParse_BerryIsRefused(t *testing.T) {
	path := write(t, `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8
  cacheKey: 10

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
`)

	pkgs, stats, err := Parse(path)
	if !errors.Is(err, ErrBerry) {
		t.Fatalf("err = %v, want ErrBerry", err)
	}
	// The refusal must be total. Returning what the v1 parser managed to make
	// of a berry file would be a partial inventory presented as a complete
	// one, which is worse than the error.
	if len(pkgs) != 0 || stats.Components != 0 {
		t.Errorf("pkgs = %+v, stats = %+v; want nothing alongside the error", pkgs, stats)
	}
	// The error names the file, so a directory scan reading several lockfiles
	// says which one it refused.
	if !errorNames(err, path) {
		t.Errorf("err = %v, want it to name %s", err, path)
	}
}

func TestParse_V1BannerBeatsALaterMetadataLine(t *testing.T) {
	// A v1 lockfile may legitimately hold a package literally named
	// __metadata, whose entry header would otherwise look like berry's block
	// marker. The banner appears first and settles it.
	path := write(t, `# yarn lockfile v1

__metadata@^1.0.0:
  version "1.0.0"
`)

	pkgs, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "__metadata" {
		t.Fatalf("packages = %+v, want the __metadata package read as v1", pkgs)
	}
}

func TestVersionField(t *testing.T) {
	cases := []struct {
		in   string
		want string
		ok   bool
	}{
		{`version "1.2.3"`, "1.2.3", true},
		{`version "1.2.3-beta.1"`, "1.2.3-beta.1", true},
		// Berry's unquoted form. Accepting it would make a berry file that
		// slipped past isBerry parse as a half-correct v1 one, which is the
		// outcome the refusal exists to prevent.
		{`version: 1.2.3`, "", false},
		{`version ""`, "", false},
		{`resolved "https://example.invalid/x.tgz"`, "", false},
		{`integrity sha512-deadbeef`, "", false},
		// A field whose name merely starts with the same letters.
		{`versionRange "^1.0.0"`, "", false},
	}

	for _, tc := range cases {
		got, ok := versionField(tc.in)
		if got != tc.want || ok != tc.ok {
			t.Errorf("versionField(%q) = %q, %v; want %q, %v", tc.in, got, ok, tc.want, tc.ok)
		}
	}
}

func TestParse_MissingFile(t *testing.T) {
	_, _, err := Parse(filepath.Join(t.TempDir(), "absent.lock"))
	if err == nil {
		t.Fatal("err = nil, want a read error")
	}
}

// errorNames reports whether err mentions path. The assertion is on the full
// path rather than "yarn.lock", which every temp directory in this file also
// contains and which would therefore pass from an error that named nothing.
func errorNames(err error, path string) bool {
	return err != nil && strings.Contains(err.Error(), path)
}
