package osrelease

import (
	"strings"
	"testing"

	"github.com/kun9497/assay/internal/pkgmeta"
)

func TestParse(t *testing.T) {
	const real = `NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.9
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
`
	d, err := Parse(strings.NewReader(real))
	if err != nil {
		t.Fatal(err)
	}
	if d.ID != "alpine" || d.VersionID != "3.19.9" || d.PrettyName != "Alpine Linux v3.19" {
		t.Errorf("Parse = %+v", d)
	}
	// The value that actually matters is the key it produces.
	eco, err := d.Ecosystem()
	if err != nil || eco != "Alpine:v3.19" {
		t.Errorf("Ecosystem() = %q, %v; want Alpine:v3.19", eco, err)
	}
}

// Quoting is not optional to handle: PRETTY_NAME is quoted and VERSION_ID is
// not, in the same real file. Keeping the quotes turns "3.19.9" into
// `"3.19.9"`, which fails the X.Y check and reports every package skipped.
func TestParse_Quoting(t *testing.T) {
	tests := []struct {
		name  string
		input string
	}{
		{"bare", "ID=alpine\nVERSION_ID=3.19.9\nPRETTY_NAME=Alpine\n"},
		{"double-quoted", "ID=\"alpine\"\nVERSION_ID=\"3.19.9\"\nPRETTY_NAME=\"Alpine\"\n"},
		{"single-quoted", "ID='alpine'\nVERSION_ID='3.19.9'\nPRETTY_NAME='Alpine'\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			d, err := Parse(strings.NewReader(tt.input))
			if err != nil {
				t.Fatal(err)
			}
			if d.ID != "alpine" || d.VersionID != "3.19.9" || d.PrettyName != "Alpine" {
				t.Errorf("Parse = %+v, want quotes stripped from every field", d)
			}
			if _, err := d.Ecosystem(); err != nil {
				t.Errorf("Ecosystem() error with parsed VersionID %q: %v", d.VersionID, err)
			}
		})
	}
}

// A file with no ID yields a zero Distro and no error: it is the caller's job
// to decide, and Distro.Ecosystem() already refuses to key an empty ID.
func TestParse_MissingFieldsAreNotAnError(t *testing.T) {
	d, err := Parse(strings.NewReader(`HOME_URL="https://example.com"` + "\n"))
	if err != nil {
		t.Fatalf("Parse() error = %v, want nil", err)
	}
	if d != (pkgmeta.Distro{}) {
		t.Errorf("Parse() = %+v, want zero Distro", d)
	}
	if _, err := d.Ecosystem(); err == nil {
		t.Error("Ecosystem() on a zero Distro should error, not key an empty ID")
	}
}

// Comments and blank lines appear in real files. Two things make this more
// than "a comment happens to lack an equals sign": one comment contains "="
// itself (as a URL query string would), and two more are commented-out
// ID/VERSION_ID assignments placed AFTER the real ones — a plausible bug is
// treating the "#" as strippable syntax rather than a whole-line skip, which
// would "uncomment" these and let them clobber the real values.
func TestParse_IgnoresCommentsAndBlanks(t *testing.T) {
	const withNoise = `# This file is autogenerated, do not edit.

ID=alpine
# ID=notarealdistro
VERSION_ID=3.19.9
# VERSION_ID=9.9.9

# see https://example.com/?ID=notarealdistro for background
PRETTY_NAME="Alpine Linux v3.19"
`
	d, err := Parse(strings.NewReader(withNoise))
	if err != nil {
		t.Fatal(err)
	}
	if d.ID != "alpine" || d.VersionID != "3.19.9" || d.PrettyName != "Alpine Linux v3.19" {
		t.Errorf("Parse = %+v", d)
	}
}

// A line that is not KEY=VALUE at all — no "=" anywhere — is noise to skip,
// not a reason to fail the whole file: os-release carries fields this parser
// does not know about, and a line's shape being wrong should not read as
// "distro identity could not be determined" any more than an unknown key does.
func TestParse_MalformedLineIsIgnoredNotAnError(t *testing.T) {
	const withGarbage = `ID=alpine
this line has no equals sign at all
VERSION_ID=3.19.9
`
	d, err := Parse(strings.NewReader(withGarbage))
	if err != nil {
		t.Fatalf("Parse() error = %v, want nil (malformed line should be ignored)", err)
	}
	if d.ID != "alpine" || d.VersionID != "3.19.9" {
		t.Errorf("Parse = %+v", d)
	}
}
