package poetrylock

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func write(t *testing.T, body string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "poetry.lock")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestParse_ReadsEveryPackageBlock(t *testing.T) {
	p := write(t, `# This file is automatically @generated by Poetry.
[[package]]
name = "django"
version = "3.2.12"
description = "A high-level Python Web framework."
optional = false
python-versions = ">=3.6"

[[package]]
name = "urllib3"
version = "1.26.5"
optional = false

[metadata]
lock-version = "2.0"
`)
	pkgs, stats, err := Parse(p)
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]string{}
	for _, pk := range pkgs {
		got[pk.Name] = pk.Version
	}
	if got["django"] != "3.2.12" || got["urllib3"] != "1.26.5" {
		t.Errorf("packages = %v, want django 3.2.12 and urllib3 1.26.5", got)
	}
	if len(pkgs) != 2 {
		t.Errorf("got %d packages, want 2 — [metadata] is not a package", len(pkgs))
	}
	if pkgs[0].Ecosystem != "PyPI" || pkgs[0].Type != "pypi" {
		t.Errorf("Ecosystem/Type = %q/%q, want PyPI/pypi", pkgs[0].Ecosystem, pkgs[0].Type)
	}
	// poetry.lock names no distro; D8's source/binary split is a distro
	// concern, and Source must stay nil rather than fabricate one — the same
	// assertion npmlock_test.go:89-93 and gomod_test.go:77-82 make for their
	// own catalogers.
	if pkgs[0].Source != nil {
		t.Errorf("Source = %+v, want nil", pkgs[0].Source)
	}
	// Locations is what --explain shows as the evidence for a finding (D10);
	// a package cataloged without it is unmatchable to the file it came from.
	if len(pkgs[0].Locations) != 1 || pkgs[0].Locations[0].Path != p {
		t.Errorf("Locations = %+v, want one entry naming %s", pkgs[0].Locations, p)
	}
	if stats.Components != stats.Cataloged+stats.SkippedNoPURL+
		stats.SkippedNoVersion+stats.SkippedUnsupportedEcosystem {
		t.Errorf("the Components == Cataloged + skips invariant does not hold: %+v", stats)
	}
}

// A key that appears AFTER the block it belongs to would be attributed to the
// next block by a parser that does not reset state at [[package]].
func TestParse_KeysDoNotLeakBetweenBlocks(t *testing.T) {
	p := write(t, `[[package]]
name = "first"
version = "1.0.0"

[[package]]
name = "second"
version = "2.0.0"
`)
	pkgs, _, err := Parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 2 || pkgs[0].Version != "1.0.0" || pkgs[1].Version != "2.0.0" {
		t.Errorf("packages = %+v, want first/1.0.0 and second/2.0.0", pkgs)
	}
}

// A block missing a version cannot be matched. Counted, never dropped.
func TestParse_ABlockWithoutAVersionIsCountedNotDropped(t *testing.T) {
	p := write(t, `[[package]]
name = "nameonly"

[[package]]
name = "complete"
version = "1.0.0"
`)
	pkgs, stats, err := Parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "complete" {
		t.Fatalf("cataloged %+v, want only 'complete'", pkgs)
	}
	if stats.Components != 2 {
		t.Errorf("Components = %d, want 2 — the incomplete block was still seen",
			stats.Components)
	}
	if stats.SkippedNoVersion != 1 {
		t.Errorf("SkippedNoVersion = %d, want 1", stats.SkippedNoVersion)
	}
}

// A "name" or "version" key inside a nested table such as [package.source]
// belongs to that table, not to the package. Attributing it to the package
// yields a wrong version, which is a silent false negative.
func TestParse_KeysInsideNestedTablesAreNotThePackages(t *testing.T) {
	p := write(t, `[[package]]
name = "real"
version = "1.0.0"

[package.source]
type = "git"
url = "https://example.com/x.git"
reference = "main"
version = "9.9.9"
`)
	pkgs, _, err := Parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("got %d packages, want 1", len(pkgs))
	}
	if pkgs[0].Version != "1.0.0" {
		t.Errorf("Version = %q, want 1.0.0 — the version inside [package.source] "+
			"belongs to that table, not to the package", pkgs[0].Version)
	}
}

// A file that is not a poetry.lock at all must not read as "no packages".
func TestParse_AFileWithNoPackageBlocksIsAnError(t *testing.T) {
	p := write(t, "this is not a lockfile\n")
	_, _, err := Parse(p)
	if err == nil {
		t.Fatal("Parse returned nil error for a file with no [[package]] blocks — " +
			"an unreadable lockfile must not read as a clean scan")
	}
	// The full path, not the bare filename: a hard-coded "poetry.lock" in the
	// error's own format string would satisfy the weaker check.
	if !strings.Contains(err.Error(), p) {
		t.Errorf("error %q does not name the file it failed on (%s)", err, p)
	}
}

// The four tests above never exercise a block that omits a field a
// PRECEDING block had — every fixture fully repopulates both name and
// version in every block it defines, which cannot tell a parser that
// resets its pending state at [[package]] apart from one that does not:
// the following block's own "name ="/"version =" lines overwrite whatever
// was there either way. This test adds the missing shape: a complete
// block immediately followed by one missing its version. A parser that
// does not reset state would let "urllib3"'s version leak into the next
// block and wrongly catalog "nameonly" as complete with urllib3's
// version — a silent false negative dressed up as a match.
func TestParse_IncompleteBlockDoesNotInheritThePreviousBlocksVersion(t *testing.T) {
	p := write(t, `[[package]]
name = "urllib3"
version = "1.26.5"

[[package]]
name = "nameonly"
`)
	pkgs, stats, err := Parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "urllib3" || pkgs[0].Version != "1.26.5" {
		t.Fatalf("cataloged %+v, want only urllib3/1.26.5 — 'nameonly' must not "+
			"pick up a version that was never in its own block", pkgs)
	}
	if stats.SkippedNoVersion != 1 {
		t.Errorf("SkippedNoVersion = %d, want 1 — 'nameonly' has no version of "+
			"its own and must not be counted as cataloged", stats.SkippedNoVersion)
	}
}

// A parser that treats every bracket header — including [metadata] — as
// starting its own package block would count [metadata] as a "seen but
// incomplete" package: Components goes up and SkippedNoVersion goes up
// together, so the Components == Cataloged + skips invariant every other
// test checks still holds — that invariant only proves the numbers add up,
// not that they are the RIGHT numbers. Only an actual [[package]] table
// may move Components.
func TestParse_NonPackageTablesDoNotInflateComponents(t *testing.T) {
	p := write(t, `[[package]]
name = "urllib3"
version = "1.26.5"

[metadata]
lock-version = "2.0"
`)
	_, stats, err := Parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if stats.Components != 1 {
		t.Errorf("Components = %d, want 1 — [metadata] is not a [[package]] "+
			"block and must not be counted as one", stats.Components)
	}
	if stats.SkippedNoVersion != 0 {
		t.Errorf("SkippedNoVersion = %d, want 0 — nothing was skipped", stats.SkippedNoVersion)
	}
}

// PEP 503 normalization (lowercasing, folding "-"/"_"/"." runs) is applied
// once, at match time, by pkgmeta.NormalizeName — not by any cataloger. A
// name is emitted exactly as poetry.lock wrote it; a stray call to
// NormalizeName (or a hand-rolled lowercase) here would be a second copy of
// that rule for it to drift out of sync with, and nothing else in this
// package's tests would catch it since every other fixture happens to
// already be lowercase.
func TestParse_NameIsNotNormalized(t *testing.T) {
	p := write(t, `[[package]]
name = "PyYAML"
version = "6.0"
`)
	pkgs, _, err := Parse(p)
	if err != nil {
		t.Fatal(err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "PyYAML" {
		t.Errorf("Name = %q, want \"PyYAML\" unchanged — normalization belongs to "+
			"pkgmeta.NormalizeName at match time, not to this cataloger", pkgs[0].Name)
	}
}
