package cargolock

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func write(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "Cargo.lock")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	return path
}

func names(t *testing.T, path string) map[string]string {
	t.Helper()
	pkgs, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	out := map[string]string{}
	for _, p := range pkgs {
		out[p.Name] = p.Version
	}
	return out
}

// Cargo.lock v1 ends with a [metadata] table whose keys are quoted strings
// naming every package and version again:
//
//	[metadata]
//	"checksum time 0.3.35 (registry+...)" = "aaa..."
//
// A parser that keeps reading after the last [[package]] block sees lines that
// do not look like fields and would be harmless — but one that treats any
// table header as "still inside the block" lets a stray assignment overwrite
// the last package. The header must close the block.
func TestParse_MetadataTableDoesNotLeakIntoTheLastPackage(t *testing.T) {
	path := write(t, `# This file is automatically @generated by Cargo.
[[package]]
name = "real-crate"
version = "1.2.3"
source = "registry+https://github.com/rust-lang/crates.io-index"

[metadata]
"checksum real-crate 1.2.3 (registry+https://github.com/rust-lang/crates.io-index)" = "abc123"
name = "not-a-package"
version = "99.99.99"
`)

	got := names(t, path)
	if len(got) != 1 {
		t.Fatalf("packages = %v, want only real-crate", got)
	}
	if got["real-crate"] != "1.2.3" {
		t.Errorf("real-crate = %q, want 1.2.3", got["real-crate"])
	}
}

// The distinguishing case for the guard above: a block whose version never
// arrived, followed by [metadata]. With both fields already set,
// first-assignment-wins protects the block on its own and the header rule looks
// redundant — the earlier test could not fail on it. Here the block is
// incomplete, so a [metadata] line IS the first version assignment and lands in
// the package unless the header closed it.
func TestParse_MetadataCannotCompleteAnIncompleteBlock(t *testing.T) {
	path := write(t, `[[package]]
name = "incomplete-crate"

[metadata]
version = "66.66.66"
`)

	pkgs, stats, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 {
		t.Fatalf("packages = %+v, want none — the version came from [metadata]", pkgs)
	}
	if stats.Components != 1 || stats.SkippedNoVersion != 1 {
		t.Errorf("stats = %d components, %d skipped; want 1 and 1", stats.Components, stats.SkippedNoVersion)
	}
}

// A block's own name is the first one in it. Some generators write dependency
// entries as tables inside the package, and a parser that lets the last
// assignment win renames the package to one of its dependencies — a name that
// is real, so the lookup succeeds and reports the wrong crate's advisories.
func TestParse_FirstAssignmentWins(t *testing.T) {
	path := write(t, `[[package]]
name = "outer-crate"
version = "1.0.0"

[[package.dependencies]]
name = "inner-crate"
version = "2.0.0"
`)

	got := names(t, path)
	if _, ok := got["outer-crate"]; !ok {
		t.Errorf("packages = %v, want outer-crate among them", got)
	}
	if got["outer-crate"] != "1.0.0" {
		t.Errorf("outer-crate = %q, want 1.0.0", got["outer-crate"])
	}
}

// Two bare assignments inside one block, with no table header between them.
// This is the only shape where first-assignment-wins and the header rule
// disagree, so it is what pins the former: uv.lock and future generators write
// repeated keys inside a block, and letting the last win renames the package to
// something that is itself a real crate, so the lookup succeeds and reports
// another package entirely.
func TestParse_RepeatedKeysInOneBlockKeepTheFirst(t *testing.T) {
	path := write(t, `[[package]]
name = "the-real-one"
version = "1.0.0"
name = "a-dependency"
version = "9.9.9"
`)

	pkgs, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 {
		t.Fatalf("packages = %+v, want one", pkgs)
	}
	if pkgs[0].Name != "the-real-one" || pkgs[0].Version != "1.0.0" {
		t.Errorf("package = %s@%s, want the-real-one@1.0.0", pkgs[0].Name, pkgs[0].Version)
	}
}

// A block with no version is counted and skipped, never dropped: a block that
// vanishes from every counter is indistinguishable from one that was never
// there, and Components == Cataloged + skips is the invariant the report uses
// to say how much of a manifest it managed to use.
func TestParse_BlockWithoutAVersionIsCountedAsSkipped(t *testing.T) {
	path := write(t, `[[package]]
name = "no-version-here"

[[package]]
name = "complete"
version = "1.0.0"
`)

	pkgs, stats, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 1 || pkgs[0].Name != "complete" {
		t.Fatalf("packages = %+v, want complete alone", pkgs)
	}
	if stats.Components != 2 || stats.SkippedNoVersion != 1 {
		t.Errorf("stats = %d components, %d skipped; want 2 and 1", stats.Components, stats.SkippedNoVersion)
	}
	if stats.Components != stats.Cataloged+stats.SkippedNoVersion {
		t.Errorf("invariant broken: %d != %d + %d", stats.Components, stats.Cataloged, stats.SkippedNoVersion)
	}
}

// A local crate — the root, or a path dependency — carries no source field.
// It is cataloged anyway rather than skipped: it is a real component of the
// tree, and skipping it would put "not evaluated" above zero on every healthy
// Rust scan, which is the defect npmlock hit with package-lock.json's root key
// and which makes --fail-on-incomplete exit 2 where nothing is wrong.
func TestParse_LocalCrateIsCataloged(t *testing.T) {
	path := write(t, `[[package]]
name = "the-workspace-root"
version = "0.1.0"
dependencies = [
 "published-dep",
]

[[package]]
name = "published-dep"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
`)

	pkgs, stats, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 2 || stats.Cataloged != 2 {
		t.Fatalf("packages = %+v, cataloged = %d; want both", pkgs, stats.Cataloged)
	}
}

func TestParse_EcosystemAndPURL(t *testing.T) {
	path := write(t, "[[package]]\nname = \"serde\"\nversion = \"1.0.196\"\n")

	pkgs, _, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	p := pkgs[0]
	// The purl type and the ecosystem key are different strings, and using
	// one where the other belongs is silent: every lookup lands in a bucket
	// that does not exist and the package reports clean.
	if p.Ecosystem != "crates.io" {
		t.Errorf("Ecosystem = %q, want crates.io", p.Ecosystem)
	}
	if p.Type != "cargo" {
		t.Errorf("Type = %q, want cargo", p.Type)
	}
	if p.PURL != "pkg:cargo/serde@1.0.196" {
		t.Errorf("PURL = %q, want pkg:cargo/serde@1.0.196", p.PURL)
	}
}

func TestStringField(t *testing.T) {
	cases := []struct {
		line string
		key  string
		want string
		ok   bool
	}{
		{`name = "serde"`, "name", "serde", true},
		{`version = "1.0.196"`, "version", "1.0.196", true},
		{`  name = "indented"`, "name", "indented", true},
		{`name="no-spaces"`, "name", "no-spaces", true},
		{`version = "1.0.0-alpha.1+build.5"`, "version", "1.0.0-alpha.1+build.5", true},
		// A different key entirely.
		{`source = "registry+https://x"`, "name", "", false},
		// A key the wanted one is a prefix of. Compared exactly, so this is
		// not a name.
		{`name_hint = "wrong"`, "name", "", false},
		// Not a quoted scalar: an array or an inline table.
		{`dependencies = [`, "dependencies", "", false},
		{`source = { registry = "x" }`, "source", "", false},
		{`name = ""`, "name", "", false},
		{`name`, "name", "", false},
	}

	for _, tc := range cases {
		got, ok := stringField(tc.line, tc.key)
		if got != tc.want || ok != tc.ok {
			t.Errorf("stringField(%q, %q) = %q, %v; want %q, %v", tc.line, tc.key, got, ok, tc.want, tc.ok)
		}
	}
}

func TestParse_EmptyLockfileIsNotAnError(t *testing.T) {
	path := write(t, "# no packages resolved\nversion = 3\n")

	pkgs, stats, err := Parse(path)
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(pkgs) != 0 || stats.Components != 0 {
		t.Errorf("pkgs = %+v, stats = %+v; want nothing", pkgs, stats)
	}
}

func TestParse_MissingFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "absent.lock")

	_, _, err := Parse(path)
	if err == nil {
		t.Fatal("err = nil, want a read error")
	}
	if !strings.Contains(err.Error(), path) {
		t.Errorf("err = %v, want it to name %s", err, path)
	}
}
